### ISSUE TITLE
Cannot open include file: 'Environment.hpp'

### ISSUE THREAD

**Issue by jhon** [CaptainProton42/GodotHoloPlayNative#1]
The code is looking for a header that is missing. I assume this is supposed to come from the godot-headers repo but I couldn't find that header in their either

**Steps to reproduce:**
1. Clone this repository locally using the github desktop client
2. Start the Visual Studio 2019 x64 Native Command Prompt
3.  Navigate the command prompt to the directory the repo was cloned to
4. `scons platform=windows`

**Expected Result:**
Native plugin compiles successfully

**Actual Result:**
```**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.10.3
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>cd \git\GodotHoloPlayNative

C:\git\GodotHoloPlayNative>scons platform=windows
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fosrc\godot_holoplay\HoloPlayVolume.obj /c src\godot_holoplay\HoloPlayVolume.cpp /TP /std:c++17 /nologo -W3 -GR -EHsc -MDd -ZI /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_DEBUG /I. /Igodot-cpp\godot-headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\gen /IHoloPlayCore\include /Iglfw\include /Iglad\include /Isrc
HoloPlayVolume.cpp
C:\git\GodotHoloPlayNative\src\godot_holoplay\HoloPlayVolume.h(4): fatal error C1083: Cannot open include file: 'Environment.hpp': No such file or directory
scons: *** [src\godot_holoplay\HoloPlayVolume.obj] Error 2
scons: building terminated because of errors.
```

**Comment by CaptainProton42** [comment]
You'll need to pull the submodules with
```
git submodule update --init --recursive
```

after you've cloned the repo and then follow the instructions from [here](https://docs.godotengine.org/en/stable/tutorials/plugins/gdnative/gdnative-cpp-example.html#building-the-c-bindings) to compile the bindings.

I'll keep this issue open until I've added that to the readme.

**Comment by jhon** [comment]
Thanks, I'm not too familiar with submodules nor used gdnative. Looks like the github desktop client handles the submodules for you. The piece I was missing was

```
cd godot-cpp
scons platform=windows generate_bindings=yes bits=64 -j8
cd ..
```

After running that command module built successfully.

**Comment by CaptainProton42** [comment]
Added better instructions to the README in 0baea32!
